### ISSUE TITLE
Call to undefined method JATSParser\Body\Par::getType()

### ISSUE THREAD

**Issue by mtoreihi** [Vitaliy-1/DOCX2JATS#3]
Hi,
Thanks for the great work you have done. We have generated an XML file from one of the DOCX files (the output shows "BUILD SUCCESSFUL"), but unfortunately upon uploading the XML in the galley section the following error shows up:
Fatal error
: Uncaught Error: Call to undefined method JATSParser\Body\Par::getType() in /home/admin/web/waocp.com/public_html/j/cache/t_compile/6267f877acd9b945f8a07db7bb24329a969a952a^%%A2^A2D^A2DEEC56%%articleMainText.tpl.php:69 Stack trace: #0 /home/admin/web/waocp.com/public_html/j/lib/pkp/lib/vendor/smarty/smarty/libs/Smarty.class.php(1870): include() #1 /home/admin/web/waocp.com/public_html/j/lib/pkp/classes/template/PKPTemplateManager.inc.php(406): Smarty->_smarty_include(Array) #2 /home/admin/web/waocp.com/public_html/j/cache/t_compile/89d777ad47fee49321727969b42b912e77adc9cd^%%2D^2D7^2D7EC92F%%article.tpl.php(30): PKPTemplateManager->_smarty_include(Array) #3 /home/admin/web/waocp.com/public_html/j/lib/pkp/lib/vendor/smarty/smarty/libs/Smarty.class.php(1257): include('/home/admin/web...') #4 /home/admin/web/waocp.com/public_html/j/lib/pkp/classes/template/PKPTemplateManager.inc.php(797): Smarty->fetch('frontend/pages/...', NULL, '89d777ad47fee49...', true) #5 /home/admin/web/waocp.com/public_html/j/lib/pkp/lib/ve in
/home/admin/web/waocp.com/public_html/j/cache/t_compile/6267f877acd9b945f8a07db7bb24329a969a952a^%%A2^A2D^A2DEEC56%%articleMainText.tpl.php
on line
69
It should be mentioned that everything works perfectly with the "example.xml" file included in the JATSParser plugin. 
Any clues to resolve the issue would be highly appreciated.

**Comment by Vitaliy-1** [comment]
Hi @mtoreihi 

You use JATS Parser plugin, right?

**Comment by Vitaliy-1** [comment]
And also can you specify what version of JATS Parser plugin you are using

**Comment by mtoreihi** [comment]
Hi @Vitaliy-1 
We are using JATS Parser 2.0.0

**Comment by Vitaliy-1** [comment]
Can you send me JATS XML that causes this error on vitaliybezsh at gmail dot com?

**Comment by mtoreihi** [comment]
I sent you an email.

**Comment by mtoreihi** [comment]
Any clues so far?

**Comment by Vitaliy-1** [comment]
Hi @mtoreihi 

Sorry, I've completely forgotten. Using your XML I'm receiving other error with latest JATS Parser plugin code: 
`Uncaught TypeError: Return value of JATSParser\Body\Table::getLabel() must be of the type string, null returned`

I've added nullable return types for the table elements, to avoid this inside JATS Parser library: https://github.com/Vitaliy-1/JATSParser/commit/f961da2ba7b271d04215ef20b98de04a57d41901

It works, but after conversion for good look the file should be manually corrected.

**Comment by helenum** [comment]
Hi Vitali

I cannot open your plugin with my Mac. Any imput?
Many thanks,

Helena
